language: ruby
rvm:
  - 3.2.2

services:
  - postgresql

before_script:
  - psql -c 'create database "apiDemo_test";' -U postgres

script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake